import {
  Sparkles,
  Hourglass,
  Swords,
  Target,
  Rocket,
  Compass,
  HelpCircle,
  Heart,
  LucideIcon,
} from 'lucide-react';

export interface Archetype {
  id: string;
  name: string;
  tagline: string;
  icon: LucideIcon;
  topics: string[];
}

export const JACK_OF_ALL_TRADES_ID = 'jack-of-all-trades';

export const SPECIFIC_ARCHETYPES: Archetype[] = [
  {
    id: 'stoic-philosopher',
    name: 'The Stoic Philosopher',
    tagline: 'Contemplative, grounded, introspective. Seeks truth while accepting what he cannot change. Finds peace in wisdom and endurance.',
    icon: Hourglass,
    topics: [
      "Fall of Roman Empire",
      "Bronze Age collapse",
      "Maya decline",
      "Black Death",
      "Stoicism",
      "Epicureanism",
      "Skepticism",
      "Problem of evil",
      "Free will vs. determinism",
      "Death, mortality, and acceptance",
      "Meaning in suffering",
      "Existential dread",
      "Forgiveness",
      "Revenge vs. justice",
      "Duty to strangers",
      "Personal identity",
      "Consciousness",
      "Panpsychism",
      "Solipsism",
      "Fatalism vs. optimistic nihilism",
      "Asceticism",
      "Occam's razor",
      "Infinite regress",
      "Ontological arguments",
      "Cosmological arguments",
      "Teleological arguments",
      "Authenticity",
      "Self-deception",
      "Self-awareness",
      "Self-compassion",
      "Character development",
      "Integrity and values",
      "Wisdom and discernment",
      "Resilience",
      "Adaptability",
      "Change management",
      "Stress management",
      "Work-life balance",
      "Patience",
      "Acceptance",
      "Surrender",
      "Spiritual exploration",
      "Entropy",
      "Heat Death",
      "Aging and telomeres",
      "Grief and coping",
      "Flow state",
      "Meditation",
      "Neuroplasticity",
      "Sleep, dreams, and circadian rhythms",
      "Memory and identity",
      "Solitude and reflection",
      "Generational wisdom",
      "Ancestry and lineage",
      "Inheritance and stewardship",
      "Personal mission",
      "Moral relativism vs. absolutism",
      "Future generations ethics",
      "Terraforming ethics",
      "Human evolution",
      "Cultural evolution",
      "Language evolution",
      "Linguistics",
      "Indus Valley civilization",
      "Spartan society",
      "Athenian democracy",
      "Roman Republic",
      "Byzantine Empire",
      "Holy Roman Empire",
      "Feudal Japan",
      "Confucianism",
      "Daoism",
      "Buddhism",
      "Advaita Vedanta",
      "Sufism",
      "Talmudic reasoning",
      "Financial anxiety",
      "Emergency funds",
      "Mindful spending",
      "Estate planning",
      "Wills and trusts",
      "Long-term perspective",
      "Generational wealth"
    ]
  },
  {
    id: 'debater',
    name: 'The Debater',
    tagline: 'Defiant, combative, anti-establishment, energized by opposition. Questions authority. Feels alive when challenged.',
    icon: Swords,
    topics: [
      "Magna Carta",
      "French Revolution",
      "American Revolution",
      "Russian Revolution",
      "Chinese Revolution",
      "Arab Spring",
      "Brexit",
      "Social contract",
      "Rousseau",
      "Nietzsche",
      "Existentialism",
      "Nihilism",
      "Absurdism",
      "Marx",
      "Foucault",
      "Derrida",
      "Anarchism",
      "Utopia vs. dystopia",
      "Cancel culture",
      "Censorship",
      "Free speech limits",
      "Whistleblowing",
      "Machiavellian statecraft",
      "Propaganda",
      "Ideology critique",
      "Postcolonial theory",
      "Patriotism vs. cosmopolitanism",
      "Cultural appropriation",
      "Identity politics",
      "Affirmative action",
      "Wealth redistribution",
      "Universal basic income",
      "Euthanasia",
      "Abortion",
      "Animal rights",
      "AI ethics",
      "Transhumanist ethics",
      "Environmental ethics",
      "Just war theory",
      "Pacifism",
      "Capital punishment",
      "Prison abolition",
      "Defund police",
      "Stanford prison experiment",
      "Conformity",
      "Obedience",
      "Groupthink",
      "Social identity theory",
      "Stereotype threat",
      "Just-world hypothesis",
      "Political polarization",
      "Gerrymandering",
      "Campaign finance",
      "Surveillance",
      "Populism",
      "Authoritarianism",
      "Democratic backsliding",
      "Disinformation",
      "Coup d'état",
      "Revolutions",
      "Guerrilla warfare",
      "Insurgency vs. terrorism",
      "Apartheid",
      "Genocide prevention",
      "International Criminal Court",
      "War crimes",
      "Sanctions",
      "Neocolonialism",
      "Campus speech",
      "Monument controversies",
      "Reparations",
      "Critical race theory",
      "Vaccine mandates",
      "Mask mandates",
      "Lockdown policies",
      "School curriculum battles",
      "Parental rights",
      "Intersectionality",
      "Allyship",
      "Woke vs. anti-woke",
      "Privilege frameworks",
      "Meritocracy",
      "Reproductive rights",
      "Sex work decriminalization",
      "Drug policy reform",
      "Restorative justice",
      "Bail reform",
      "Collective guilt",
      "Truth and reconciliation",
      "Assertiveness",
      "Conflict resolution",
      "Criticism handling",
      "Personal boundaries",
      "Self-confidence",
      "Networking",
      "Student loan strategies",
      "Debt management",
      "Tax filing",
      "Credit score",
      "Wealth inequality",
      "Economic mobility"
    ]
  },
  {
    id: 'strategic-genius',
    name: 'The Strategic Genius',
    tagline: 'Calculating, razor-sharp, patient, methodical. Sees patterns others miss. Controls outcomes through planning.',
    icon: Target,
    topics: [
      "Game Theory",
      "Information Theory",
      "Bayesian Thinking",
      "Probability",
      "Prime Numbers",
      "Second-Order Thinking",
      "Antifragility",
      "Occam's razor",
      "Hanlon's Razor",
      "Porter's Five Forces",
      "SWOT analysis",
      "PESTEL analysis",
      "Business Model Canvas",
      "Lean Startup",
      "Minimum Viable Product",
      "Supply chain optimization",
      "Just-in-time inventory",
      "Network effects",
      "Competitive moats",
      "Economies of scale",
      "Economies of scope",
      "First-mover advantage",
      "Late-mover advantage",
      "Pivoting",
      "Burn rate",
      "Runway",
      "Due diligence",
      "BATNA",
      "Win-win negotiation",
      "Sales funnel",
      "Customer lifetime value",
      "Customer acquisition cost",
      "Churn rate",
      "Net Promoter Score",
      "OKRs",
      "KPIs",
      "Balanced Scorecard",
      "Corporate culture",
      "Talent acquisition",
      "Modern Portfolio Theory",
      "CAPM",
      "Black-Scholes",
      "Efficient market hypothesis",
      "Random walk theory",
      "Technical analysis",
      "Fundamental analysis",
      "Value investing",
      "Growth investing",
      "Momentum investing",
      "Dollar-cost averaging",
      "Asset allocation",
      "Sharpe ratio",
      "Alpha and beta",
      "Hedge funds",
      "Private equity",
      "Leveraged buyouts",
      "Arbitrage",
      "Prisoner's dilemma",
      "Tragedy of the commons",
      "Public choice theory",
      "Moral hazard",
      "Adverse selection",
      "Signaling theory",
      "Auction theory",
      "Bidding strategies",
      "Winner's curse",
      "Military strategy",
      "Sun Tzu",
      "Clausewitz",
      "Maneuver warfare",
      "Siege warfare",
      "Naval strategy",
      "Air power",
      "Cyber warfare",
      "Counterinsurgency",
      "Intelligence gathering",
      "Counterintelligence",
      "Covert action",
      "OPSEC",
      "Scenario planning",
      "War gaming",
      "Red teaming",
      "Systems thinking",
      "Threat modeling",
      "Goal setting",
      "Habit formation",
      "Productivity methods",
      "Time management",
      "Focus and attention",
      "Decision-making skills",
      "Problem-solving mindset",
      "Career planning",
      "Personal branding",
      "Skill acquisition",
      "Credit score management",
      "Credit cards",
      "Rewards",
      "Loans",
      "Interest rates",
      "Mortgages",
      "Renting vs. buying",
      "Personal budgeting",
      "Saving strategies",
      "Retirement planning",
      "401(k)",
      "IRAs",
      "Compound interest",
      "Investment basics",
      "Risk tolerance",
      "Financial independence",
      "FIRE movement",
      "Insurance basics",
      "Reading fine print",
      "Avoiding scams"
    ]
  },
  {
    id: 'visionary',
    name: 'The Visionary',
    tagline: 'Forward-looking, idealistic, restless. Sees what could be, not what is. Driven by possibility.',
    icon: Rocket,
    topics: [
      "Renaissance",
      "Age of Exploration",
      "Space Race",
      "Industrial Revolution",
      "Meiji Restoration",
      "Big Bang theory",
      "Inflationary universe",
      "Multiverse",
      "Wormholes",
      "Time travel",
      "Quantum computing",
      "Nuclear fusion",
      "CRISPR gene editing",
      "Human Genome Project",
      "Artificial general intelligence",
      "Brain-computer interfaces",
      "Bioprinting",
      "Nanotechnology",
      "Space elevators",
      "Mars colonization",
      "Dyson Sphere",
      "Kardashev Scale",
      "Hypersonic travel",
      "Hyperloop",
      "Smart cities",
      "Vertical farming",
      "Lab-grown meat",
      "Carbon capture",
      "Direct air capture",
      "6G",
      "Satellite internet",
      "Autonomous vehicles",
      "Soft robotics",
      "Exoskeletons",
      "Augmented reality",
      "Virtual reality",
      "Mixed reality",
      "Digital twins",
      "Telemedicine",
      "Bioinformatics",
      "Gene sequencing",
      "Nanobots in medicine",
      "Longevity research",
      "Rejuvenation",
      "Cryonics",
      "Digital immortality",
      "Uploading consciousness",
      "Simulation Hypothesis",
      "Holographic universe",
      "Transhumanism",
      "Singularity",
      "Space settlements",
      "O'Neill cylinders",
      "Terraforming",
      "Interstellar travel",
      "Warp drives",
      "Quantum internet",
      "DAOs",
      "Decentralized society",
      "Post-scarcity economics",
      "Resource-based economy",
      "Regenerative cities",
      "Circular economy",
      "Zero-waste",
      "Geoengineering",
      "Rewilding",
      "De-extinction",
      "Synthetic biology",
      "Bio-design",
      "Floating cities",
      "Underwater habitats",
      "Lunar bases",
      "Asteroid mining",
      "Venus colonies",
      "Europa exploration",
      "Breakthrough Starshot",
      "First contact protocols",
      "Xenolinguistics",
      "Lifelong learning",
      "Legacy thinking",
      "Personal mission",
      "Purpose and meaning",
      "Creativity cultivation",
      "Innovation mindset",
      "Cultural intelligence",
      "FIRE movement",
      "Financial independence",
      "Generational wealth",
      "Impact investing",
      "ESG",
      "Economic mobility",
      "Geographic arbitrage",
      "Location-independent income"
    ]
  },
  {
    id: 'explorer',
    name: 'The Explorer',
    tagline: 'Curious, adventurous, endlessly fascinated. Loves the unknown. Finds joy in discovery.',
    icon: Compass,
    topics: [
      "Polynesian navigation",
      "Viking explorations",
      "Columbus voyages",
      "Lewis and Clark expedition",
      "Age of Exploration",
      "Silk Road",
      "Gold rushes",
      "Panama Canal",
      "Suez Canal",
      "SETI",
      "Exoplanet detection",
      "Deep-sea vents",
      "Extremophiles",
      "Astrobiology",
      "Amazon rainforest",
      "Mariana Trench",
      "Ocean currents",
      "Antarctic expeditions",
      "Arctic expeditions",
      "Mountaineering",
      "Cave diving",
      "Jungle survival",
      "Desert survival",
      "Archaeology",
      "Paleontology",
      "Fossil digs",
      "Hominid finds",
      "Ancient DNA",
      "Shipwreck archaeology",
      "Underwater archaeology",
      "Hubble Space Telescope",
      "James Webb Space Telescope",
      "Neutrino detectors",
      "Gravitational wave observatories",
      "Citizen science",
      "Birdwatching",
      "Botany",
      "Mycology",
      "Entomology",
      "Marine biology",
      "Primate studies",
      "Whale research",
      "Elephant communication",
      "Wolf pack dynamics",
      "Penguin colonies",
      "Animal tracking",
      "Wildlife photography",
      "Night sky observation",
      "Meteor showers",
      "Eclipses",
      "Aurora hunting",
      "Bioluminescence",
      "Coral reefs",
      "Rainforest canopies",
      "Deserts",
      "Tundra",
      "Glaciers",
      "Volcanoes",
      "Caves",
      "River source expeditions",
      "Island discoveries",
      "Nomadic cultures",
      "Indigenous knowledge",
      "Ethnobotany",
      "Traditional medicine",
      "Fermentation",
      "Ancient recipes",
      "Lost crafts",
      "Traditional music",
      "Language documentation",
      "Dialects",
      "Oral history",
      "Folklore",
      "Mythology",
      "Dream traditions",
      "Psychedelic research",
      "Consciousness exploration",
      "Meditation",
      "Breathwork",
      "Martial arts",
      "Dance anthropology",
      "Ritual studies",
      "Festivals",
      "Culinary tourism",
      "Road trips",
      "Train travel",
      "Sailing",
      "Long-distance hiking",
      "Bike touring",
      "Backpacking",
      "Hostel culture",
      "Couchsurfing",
      "Work exchange",
      "Teaching abroad",
      "Language immersion",
      "Homestays",
      "Volunteering",
      "Study abroad",
      "Gap years",
      "Sabbaticals",
      "Retreats",
      "Vision quests",
      "Pilgrimages",
      "Camino de Santiago",
      "Hajj",
      "Kumbh Mela",
      "Burning Man",
      "Lifelong learning",
      "Skill acquisition",
      "Hobbies and passions",
      "Reading habits",
      "Leisure and play",
      "Active listening",
      "Networking",
      "Cultural intelligence",
      "Risk tolerance",
      "Alternative investments",
      "Geographic arbitrage",
      "Location-independent income"
    ]
  },
  {
    id: 'skeptic',
    name: 'The Skeptic',
    tagline: 'Cautious, distrustful, never fully convinced. Questions everything, especially popular narratives.',
    icon: HelpCircle,
    topics: [
      "Philosophical skepticism",
      "Rationalism vs. empiricism",
      "Cartesian dualism",
      "Problem of evil",
      "Free will vs. determinism",
      "Moral relativism",
      "Placebo effect",
      "Nocebo effect",
      "Confirmation bias",
      "Anchoring effect",
      "Availability heuristic",
      "Dunning-Kruger effect",
      "Hindsight bias",
      "Optimism bias",
      "Overconfidence effect",
      "Sunk cost fallacy",
      "Loss aversion",
      "Endowment effect",
      "Fundamental attribution error",
      "Actor-observer asymmetry",
      "Just-world hypothesis",
      "Impostor syndrome",
      "Bystander effect",
      "Halo effect",
      "Mere exposure effect",
      "Priming",
      "Classical conditioning",
      "Operant conditioning",
      "Learned helplessness",
      "Fixed mindset",
      "Growth mindset",
      "System 1 thinking",
      "System 2 thinking",
      "Prospect theory",
      "Choice overload",
      "Decision paralysis",
      "Fear and phobia origins",
      "Anxiety disorders",
      "Depression",
      "OCD",
      "Schizophrenia",
      "Psychopathy",
      "Stockholm syndrome",
      "Munchausen syndrome",
      "Factitious disorders",
      "Malingering",
      "Lie detection",
      "Polygraph reliability",
      "Eyewitness fallibility",
      "False memory",
      "Recovered memory",
      "Alien abduction claims",
      "UFO sightings",
      "Crop circles",
      "Miracle claims",
      "Faith healing",
      "Psychic abilities",
      "ESP",
      "Remote viewing",
      "Telekinesis",
      "Ghost hunting",
      "EVP",
      "Hauntings",
      "Demon possession",
      "Exorcism",
      "Near-death experiences",
      "Out-of-body experiences",
      "Past-life regression",
      "Astrology",
      "Horoscopes",
      "Palmistry",
      "Tarot",
      "Numerology",
      "Feng shui",
      "Crystal healing",
      "Reiki",
      "Homeopathy",
      "Acupuncture",
      "Chiropractic",
      "Naturopathy",
      "Herbal supplements",
      "Detoxification",
      "Alkaline diet",
      "Antioxidants",
      "Vitamin megadosing",
      "Colloidal silver",
      "Essential oils",
      "Aromatherapy",
      "Music therapy",
      "Art therapy",
      "Pet therapy",
      "Equine therapy",
      "Wilderness therapy",
      "Scared Straight program",
      "DARE program",
      "Abstinence-only education",
      "Learning styles",
      "Multiple intelligences",
      "Standardized testing",
      "Grade inflation",
      "College ROI",
      "Online learning",
      "Unschooling",
      "School choice",
      "Vouchers",
      "Charter schools",
      "Homeschooling outcomes",
      "Teacher tenure",
      "Class size",
      "Uniforms",
      "Zero tolerance",
      "Police in schools",
      "Criticism handling",
      "Failure and growth",
      "Productivity methods",
      "Judgment development",
      "Emotional regulation",
      "Personal boundaries",
      "Financial anxiety",
      "Risk tolerance",
      "Insurance basics",
      "Due diligence",
      "Reading fine print",
      "Avoiding scams",
      "Credit score"
    ]
  },
  {
    id: 'romantic',
    name: 'The Romantic',
    tagline: 'Passionate, idealistic, emotionally driven. Sees beauty and meaning everywhere. Lives for the extraordinary.',
    icon: Heart,
    topics: [
      "Cleopatra's reign",
      "Romantic love chemistry",
      "Friendship formation",
      "Jealousy",
      "Envy",
      "Empathy",
      "Trust",
      "Oxytocin",
      "Laughter",
      "Crying",
      "Body language",
      "Micro-expressions",
      "Eye contact",
      "Personal space",
      "Status",
      "Dominance",
      "Shame",
      "Guilt",
      "Pride",
      "Hubris",
      "Humiliation",
      "Attachment styles",
      "Parenting styles",
      "Temperament types",
      "Emotional intelligence",
      "Beauty and aesthetic judgment",
      "Art and emotion",
      "Poetry and feeling",
      "Music and emotion",
      "Film and catharsis",
      "Literature and empathy",
      "Theater",
      "Dance",
      "Photography and memory",
      "Architecture and emotion",
      "Design and meaning",
      "Fashion and identity",
      "Style",
      "Tattoos and personal narrative",
      "Body art",
      "Scent and memory",
      "Taste and emotional response",
      "Touch and connection",
      "Nature and awe",
      "Landscapes",
      "Seascapes",
      "Mountains",
      "Forests",
      "Deserts",
      "Storms",
      "Sunsets",
      "Sunrises",
      "Night",
      "Moon",
      "Stars",
      "Ocean",
      "Rivers",
      "Waterfalls",
      "Flowers",
      "Gardens",
      "Seasons",
      "Autumn",
      "Spring",
      "Winter",
      "Summer",
      "Light and shadow",
      "Color",
      "Texture",
      "Sound",
      "Silence",
      "Movement",
      "Stillness",
      "Childhood memories",
      "First experiences",
      "Personal milestones",
      "School days",
      "College years",
      "First job",
      "Family traditions",
      "Holiday celebrations",
      "Birthday memories",
      "Old photographs",
      "Vintage objects",
      "Retro fashion",
      "Old songs",
      "Classic movies",
      "Old books",
      "Childhood home",
      "Neighborhood changes",
      "Lost friendships",
      "Past relationships",
      "Life chapters",
      "Personal transformation",
      "Coming-of-age stories",
      "Cultural touchstones",
      "Shared generational memories",
      "Historical nostalgia",
      "Home and memory",
      "First love",
      "Loss and longing",
      "Hope and anticipation",
      "Wonder",
      "Curiosity",
      "Desire",
      "Passion",
      "Tenderness",
      "Vulnerability",
      "Leap of faith",
      "Trust and betrayal",
      "Forgiveness and healing",
      "Celebration",
      "Joy",
      "Sorrow",
      "Anger",
      "Fear",
      "Surrender",
      "Gratitude",
      "Reverence",
      "Awe",
      "Sacred and profane",
      "Ceremony and ritual",
      "Tradition and continuity",
      "Heritage and identity",
      "Roots and wings",
      "Storytelling",
      "Myth",
      "Legend",
      "Hero's journey",
      "Love story archetypes",
      "Tragedy and catharsis",
      "Comedy and connection",
      "Fairy tales and longing",
      "Dreams and desire",
      "Poetry and soul",
      "Music and transcendence",
      "Dance and celebration",
      "Festivals",
      "Gatherings",
      "Hospitality",
      "Marriage",
      "Friendship",
      "Loyalty",
      "Family",
      "Community",
      "Humanity",
      "Kindness",
      "Self-compassion",
      "Emotional regulation",
      "Personal boundaries",
      "Communication skills",
      "Active listening",
      "Purpose and meaning",
      "Authenticity",
      "Money and relationships",
      "Mindful spending",
      "Giving and gifting",
      "Financial anxiety",
      "Generational wealth"
    ]
  }
];

export const JACK_OF_ALL_TRADES_ARCHETYPE: Archetype = {
  id: JACK_OF_ALL_TRADES_ID,
  name: 'The Jack of all Trades',
  tagline: 'Versatile, open-minded, inquisitive. Draws topics at random across all archetypes.',
  icon: Sparkles,
  topics: Array.from(new Set(SPECIFIC_ARCHETYPES.flatMap((a) => a.topics)))
};

export const ALL_ARCHETYPES: Archetype[] = [
  JACK_OF_ALL_TRADES_ARCHETYPE,
  ...SPECIFIC_ARCHETYPES,
];

export function getRandomTopicForArchetype(
  archetypeId: string,
  currentTopic?: string
): string {
  let topicPool: string[] = [];

  if (archetypeId === JACK_OF_ALL_TRADES_ID) {
    topicPool = JACK_OF_ALL_TRADES_ARCHETYPE.topics;
  } else {
    const found = SPECIFIC_ARCHETYPES.find((a) => a.id === archetypeId);
    topicPool = found ? found.topics : JACK_OF_ALL_TRADES_ARCHETYPE.topics;
  }

  if (topicPool.length === 0) {
    return 'General Topic';
  }

  if (topicPool.length === 1) {
    return topicPool[0];
  }

  // Filter out current topic to ensure a fresh spin when possible
  const filtered = topicPool.filter((t) => t !== currentTopic);
  const pool = filtered.length > 0 ? filtered : topicPool;

  const randomIndex = Math.floor(Math.random() * pool.length);
  return pool[randomIndex];
}
